/* global window */
// Portfolio content — extracted from Experience.docx and Personality.docx
window.PORTFOLIO = {
  owner: {
    name: "Sanjana Kanchibotla",
    initials: "SK",
    role: "Data Scientist · Product Thinker",
    location: "Toronto, ON",
    email: "sanjanakanchibotla@gmail.com",
    links: {
      github: "https://github.com/sanjxksl",
      linkedin: "https://linkedin.com/in/sanjanaksl",
    },
    tagline: "I find the problems worth solving, then use whatever it takes to solve them.",
  },

  folders: [
    { id: "work", name: "Work", kind: "folder" },
    { id: "projects", name: "Projects", kind: "folder" },
    { id: "competitions", name: "Competitions", kind: "folder" },
    { id: "learning", name: "Learning", kind: "folder" },
    { id: "about", name: "About_Me", kind: "folder" },
  ],

  work: [
    {
      id: "cibc",
      name: "CIBC — AI Solutions",
      type: "EXP",
      date: "Jan 2026 — Present",
      role: "Global Methodology Programs & Strategy",
      location: "Toronto, Canada",
      kicker: "Current · Finance · Enterprise AI",
      title: "AI-driven exam-scoping assistant for <em>AML examiners</em>",
      subtitle: "Agent + RAG + LLM insight layer, embedded with the CEEP team.",
      body: [
        { h: "Context", p: "Enterprise AML and Compliance exams are fast-paced, high-stakes, and run on confidential, unstructured data scattered across multiple repositories. Examiners lose days understanding prior scopes, locating the right document versions, and identifying coverage gaps." },
        { h: "Approach", p: "Spent two weeks embedded with the team — interviews, ethnographic observation, prioritising real pain points before proposing a solution. Scoped a proactive AI agent that doubles as a centralised repository and smart search engine." },
        { h: "What it does", list: [
          "From a line of business or tentative scope element, retrieves the most relevant documents ranked by relevance — plus templates, prior issues, risk ratings, and emerging insights driven by news and recent changes.",
          "Inline chatbot for document-specific Q&A so examiners don't hunt through huge reports.",
          "RAG over historical exam reports with a roadmap to wire Databricks for automated ingestion and a second LLM trained on domain news for a proactive insight layer.",
        ]},
        { h: "Craft", p: "Deployed in Streamlit with an examiner-friendly configuration UI. Managed version control via GitHub for traceability across model, data, and UI changes. Defined a future evaluation framework using simulated, real-life-inspired case scenarios for continuous quality improvement." },
      ],
      tags: ["RAG", "LLM", "Streamlit", "Databricks", "Ethnographic Research"],
      metrics: [
        { v: "2 wks", l: "embedded research" },
        { v: "100+", l: "annual reviews scoped" },
        { v: "~0", l: "to near-instant retrieval" },
      ],
    },
  ],

  projects: [
    {
      id: "credit-risk",
      name: "credit_risk.py",
      type: "ML",
      date: "2025",
      kicker: "Financial ML · Explainable AI · Fairness",
      title: "Credit risk with <em>counterfactual explanations</em>",
      subtitle: "Predict loan default, and tell rejected applicants what to change.",
      body: [
        { p: "Binary classification on 148,670 applications, 31 raw → 68 engineered features. The goal wasn't just a good AUC — it was telling a rejected borrower what would actually flip their outcome." },
        { h: "Pipeline", list: [
          "Median imputation, winsorization at 1st/99th for loan amount, property value, income, LTV, DTIR1.",
          "Log-transformed skewed continuous vars; one-hot encoded categoricals; StandardScaler.",
          "SMOTE with sampling_strategy=0.5 → 33.3% default rate in train while preserving test calibration (24.6% actual).",
          "is_standard_term binary feature (1 if term = 360 mo).",
        ]},
        { h: "Model", p: "3-layer MLP (128 / 64 / 32) with BatchNorm, ReLU, progressive dropout (0.3 / 0.2 / 0.1). Adam + weight decay 1e-4, early stopping (patience 15), ReduceLROnPlateau. 19,649 parameters. Validated that a 2-3 layer MLP outperforms deeper ResNet-style architectures on structured tabular data." },
        { h: "Calibration & Fairness", p: "Platt Scaling on validation preds: calibration gap 3.0% → 0.1%, Brier 0.0813 → 0.0799. Fairness audit across gender/age/region: max calibration gap 1.1%, Disparate Impact Ratio 1.021 (passes 80% rule)." },
        { h: "Counterfactuals", p: "Generated recourse for 13 high-risk borrowers using DiCE, bounded to 5th–95th percentile. 100% success across 46 counterfactuals. Avg 2.2 feature changes per recommendation — LTV, DTIR, and loan term the most frequently modified actionable features." },
      ],
      tags: ["PyTorch", "DiCE", "SMOTE", "Platt Scaling", "Fairness"],
      metrics: [
        { v: "88.8%", l: "test AUC-ROC" },
        { v: "0.83", l: "AUC-PR" },
        { v: "100%", l: "counterfactual success" },
        { v: "1.02", l: "DIR — fairness" },
      ],
    },
    {
      id: "evidence-engine",
      name: "evidence_engine.py",
      type: "AI",
      date: "2025",
      kicker: "PM Tooling · LLM · Bias Mitigation",
      title: "Evidence Engine for <em>product decisions</em>",
      subtitle: "Help PMs synthesize messy research into defensible, traceable insights.",
      body: [
        { p: "Prioritization frameworks like RICE get gamed by bias because the inputs — evidence — are never rigorously gathered or challenged before scoring begins. This tool sits one step upstream." },
        { h: "Architecture", p: "Modular Streamlit app on Google Gemini: evidence extractor, synthesizer, intent classifier, output generator, transparent reasoning tracer, SQLite persistence." },
        { h: "Modes", p: "LLM-based intent classification routes queries across hypothesis testing, pattern identification, confidence assessment, stakeholder reporting, and assumption validation." },
        { h: "Transparency", p: "Reasoning traces expose supporting and counter-evidence for every verdict, classifying evidence into six types: user quotes, behavioural observations, support tickets, analytics, stakeholder input, competitor intel." },
        { h: "Research Foundation", p: "Built on a literature review of Kahneman-Tversky and Morewedge et al. on HiPPO bias, confirmation bias, anchoring. Validated through interviews with practicing PMs." },
      ],
      tags: ["Gemini", "Streamlit", "Prompt Eng.", "SQLite", "User Research"],
      metrics: [
        { v: "6", l: "evidence types" },
        { v: "5", l: "intent modes" },
        { v: "4", l: "PMs interviewed" },
      ],
    },
    {
      id: "aesthify",
      name: "aesthify.py",
      type: "CV",
      date: "2025",
      kicker: "Computer Vision · Design Research",
      title: "Aesthify — quantifying <em>subjective taste</em>",
      subtitle: "Rule-based design scores vs. what 101 people actually prefer.",
      body: [
        { p: "Design aesthetics is subjective and cannot be fitted into one regression line. So this tool moves from designer-centric to user-centric: it gives teams a way to discover which aesthetic principles matter to their target audience." },
        { h: "Pipeline", p: "Flask app integrating YOLOv8 + Roboflow for object detection on interior images. Rule-based scores for 7 principles: balance, proportion, symmetry, simplicity, harmony, contrast, unity." },
        { h: "Study", p: "Collected aesthetic ratings from 101 participants. Correlation analysis between computed scores and human ratings; demographic clustering to identify perception patterns by geography and background." },
        { h: "Findings", list: [
          "Simplicity correlated most strongly with preference (r = 0.68).",
          "Symmetry negatively correlated (r = -0.60) — users preferred asymmetric layouts.",
          "Aesthetic judgment varied significantly across demographic groups.",
        ]},
        { h: "Stack", p: "Python 3.10, Flask, OpenCV, YOLOv8, Roboflow, Pandas, Scikit-learn." },
      ],
      tags: ["YOLOv8", "Flask", "User Study", "Clustering"],
      metrics: [
        { v: "101", l: "participants" },
        { v: "r=0.68", l: "simplicity ↔ preference" },
        { v: "7", l: "design principles" },
      ],
    },
    {
      id: "us-income",
      name: "us_income.py",
      type: "DL",
      date: "2025",
      kicker: "Deep Learning · Tabular",
      title: "US Census income prediction",
      subtitle: "A reliable NN on imbalanced tabular data where naïve approaches fail.",
      body: [
        { p: "Binary classification above/below $50K on US Census. 75/25 class split, 90 features after preprocessing." },
        { h: "Preprocessing", p: "Median imputation (numeric), most-frequent (categorical). MinMaxScaler preferred over StandardScaler after a 2% accuracy gain in experimentation. One-hot via ColumnTransformer." },
        { h: "Feature Engineering", p: "gain_loss_ratio = (capital-gain+1)/(capital-loss+1); total_capital = capital-gain − capital-loss. Empirically validated: adding more than 2 engineered features degraded performance." },
        { h: "Model", p: "2 hidden layers [256, 128], ReLU + BatchNorm + Dropout 0.3, Adam lr 0.001. Deeper architectures ([512,256,128,64]) dropped to 82–83% due to noise amplification — a lesson worth keeping." },
        { h: "Training", p: "5-fold stratified ensemble; minority class weight 1.2x; threshold optimised 0.5 → 0.70 after a sweep over 0.30–0.70." },
      ],
      tags: ["Keras", "k-fold", "Threshold Tuning"],
      metrics: [
        { v: "85.6%", l: "accuracy" },
        { v: "0.91", l: "AUC-ROC" },
        { v: "0.70", l: "F1" },
      ],
    },
    {
      id: "alumni-career",
      name: "alumni_career.py",
      type: "DS",
      date: "2025",
      kicker: "Predictive Analytics · Data Cleaning",
      title: "Alumni career success prediction",
      subtitle: "Scattered, inconsistent institutional data → one analysis-ready view.",
      body: [
        { p: "Merged four fragmented IIITDM alumni CSVs with heterogeneous salary formats (USD, INR, lakhs p.a., monthly). Built a data preparation pipeline to standardise, convert, and unify records." },
        { h: "Modelling", list: [
          "Random Forest Regressor for salary prediction; GridSearchCV with 5-fold CV; MAE + R².",
          "Random Forest Classifier for above/below-median success; balanced class weights; accuracy, ROC-AUC, precision/recall.",
        ]},
        { h: "Insight", p: "Geography matters more than job title — the same role shows 3x salary variance by country." },
      ],
      tags: ["Random Forest", "GridSearchCV", "Data Cleaning"],
      metrics: [
        { v: "3,300+", l: "records unified" },
        { v: "4", l: "datasets merged" },
        { v: "3x", l: "geo salary variance" },
      ],
    },
  ],

  competitions: [
    {
      id: "koru",
      name: "koru_problem_hunt.md",
      type: "CASE",
      date: "Nov 2025",
      kicker: "1st Place · Problem Discovery",
      title: "Koru Problem Hunt — <em>ThirdPlace</em>",
      subtitle: "Mixed-methods research, a dual-sided marketplace, and the 'friction trinity'.",
      body: [
        { h: "Research", p: "Quantitative survey (79% aged 18–24, equal gender split) + 8 in-depth 30-minute qualitative interviews across hobbyists and studio owners." },
        { h: "The Friction Trinity", list: [
          "Cost — 82%",
          "Schedule fit — 84%",
          "Discovery — 90%",
        ]},
        { h: "Studio side", p: "51% average underutilisation. $300 lost revenue per empty 10-person ceramics class. 40–60% empty capacity industry-wide." },
        { h: "Segmentation", p: "Two behavioural profiles — Explorers (variety seekers) and Connectors (community builders). Recommended Connectors as initial target for higher retention." },
        { h: "Sizing", p: "TAM $45B+ · SAM $3.6B · SOM $9–15M over 3 years." },
        { h: "Design", p: "ThirdPlace: dual-sided social marketplace, credit-based subscription (8/16/32-credit plans with rollover), opt-in adaptive pricing for off-peak, transparent commission lower than Groupon's 50%." },
        { h: "Validation", p: "Hypothesis register across desirability / feasibility / viability with 5 hypotheses, each assigned risk, evidence classification, and specific experiment design." },
      ],
      tags: ["User Research", "Mixed-Methods", "Marketplace", "Strategy"],
      metrics: [
        { v: "1st", l: "of all teams" },
        { v: "8", l: "interviews" },
        { v: "$3.6B", l: "SAM" },
      ],
    },
    {
      id: "mma",
      name: "mma_datathon.md",
      type: "CASE",
      date: "Jan 2026",
      kicker: "1st Place · Causal Inference",
      title: "Rotman MMA Datathon",
      subtitle: "6,865+ hours of web traffic, causal inference, and a $75–90K reallocation.",
      body: [
        { p: "Competed in the Rotman MMA Datathon, placing 1st of all participating teams." },
        { h: "Data", p: "6,865+ hours of web traffic for a retail brand operating across Canada and the US, evaluating paid search campaign effectiveness." },
        { h: "Method", p: "Applied causal inference to isolate true campaign impact from organic traffic, separating signal from noise — not naïve correlation." },
        { h: "Finding", p: "35% positive ROI in US markets; loss-making spend in Canada." },
        { h: "Recommendation", p: "Reallocate $75–90K in paid search budget from Canada to the US." },
      ],
      tags: ["Causal Inference", "Marketing Analytics", "Python"],
      metrics: [
        { v: "1st", l: "place" },
        { v: "35%", l: "US ROI" },
        { v: "$75–90K", l: "reallocation" },
      ],
    },
    {
      id: "rdc",
      name: "rdc_compass.md",
      type: "CASE",
      date: "Mar 2026",
      kicker: "Finals · Top 7 of 43 · FinTech",
      title: "Rotman Design Challenge — <em>Compass</em>",
      subtitle: "LLM agent inside Manulife's app, for a health-wealth feedback loop.",
      body: [
        { p: "Designed Compass, an LLM-powered AI agent embedded in Manulife's app, integrating Group Benefits, Vitality, and Individual Insurance data. Reached finals (top 7 of 43 teams) at RDC 2026." },
        { h: "Architecture", list: [
          "Conversational LLM interface.",
          "Smart data retrieval trained on domain-specific insurance data.",
          "Event-trigger engine responding to life signals (job change, new dependent, policy renewal).",
        ]},
        { h: "Research", p: "7 empathy interviews + 38 survey responses. 73% of users left health benefits unused — a navigability failure, not a product failure." },
        { h: "Validation", list: [
          "87% would use the tool to find unused benefits.",
          "79% to understand coverage.",
          "62% rated usefulness 7–10/10.",
          "62% said it would change their view of Manulife.",
        ]},
      ],
      tags: ["LLM", "FinTech", "Prototype", "User Research"],
      metrics: [
        { v: "7/43", l: "finalists" },
        { v: "73%", l: "benefits unused" },
        { v: "87%", l: "would adopt" },
      ],
    },
  ],

  learning: [
    { hash: "7a2c19f", date: "2026·Q2", branch: "data-science",
      msg: "Ship Compass — LLM agent for Manulife (RDC finals)",
      desc: "Three-layer architecture with event triggers on life signals. The health-wealth feedback loop is real and measurable.",
      current: true },
    { hash: "e4f1b03", date: "2026·Q1", branch: "data-science",
      msg: "CIBC: embedded fieldwork → RAG agent for AML scoping",
      desc: "Two weeks of ethnographic work before any architecture. The interface decision came from watching examiners work, not from reading docs." },
    { hash: "c9a7d51", date: "2026·Q1", branch: "causal-inference",
      msg: "1st place — MMA Datathon",
      desc: "Causal inference on paid-search traffic. Learned to separate signal from correlation before recommending a $75–90K spend shift." },
    { hash: "b3e8217", date: "2025·Q4", branch: "product",
      msg: "1st place — Koru Problem Hunt (ThirdPlace)",
      desc: "Mixed-methods research, the friction trinity, behavioural segmentation. The research came before the product, not after." },
    { hash: "5d94a8e", date: "2025·Q4", branch: "explainable-ai",
      msg: "Credit risk + counterfactual explanations",
      desc: "Stopped at 88.8% AUC-ROC for about an hour. The real work was giving rejected borrowers a path forward." },
    { hash: "2f1c6b9", date: "2025·Q3", branch: "llm",
      msg: "Evidence Engine — bias mitigation for PM decisions",
      desc: "Literature review (Kahneman-Tversky, Morewedge et al.) before a single line of code. The bug was in the inputs, not the framework." },
    { hash: "a8d3e45", date: "2025·Q3", branch: "deep-learning",
      msg: "US Census income — 5-fold NN ensemble",
      desc: "First serious deep learning project. Lesson: deeper isn't better on tabular — two layers beat four every time." },
    { hash: "f7b2091", date: "2025·Q2", branch: "rotman",
      msg: "Begin MMA at Rotman — deliberate depth shift",
      desc: "Technical depth before product authority. The sequencing is the point." },
    { hash: "91c5a7f", date: "2025·Q1", branch: "cv",
      msg: "Aesthify — computer vision meets 101 real opinions",
      desc: "Proved you can quantify aesthetics — and that the model's opinion matters less than the user's." },
    { hash: "3e7d812", date: "2024·Q3", branch: "engineering",
      msg: "Ashok Leyland — GT-Suite engine simulation",
      desc: "Brake torque error ±3%, model accuracy >97%. But the bigger lesson: understanding the system matters more than the precision." },
    { hash: "c0b1d9a", date: "2024·Q2", branch: "product",
      msg: "HyperHorizon — GTM for autonomous underwater vehicles",
      desc: "22 competitors researched, 4 government competitions won. Ownership learned the hard way in a messy startup." },
    { hash: "41a8e36", date: "2023·Q3", branch: "leadership",
      msg: "Founded Red Ribbon Society · 300+ participants served",
      desc: "Built institutional structures that outlasted me. The SOPs mattered more than the events." },
  ],

  personality: {
    quote: "I cannot engage with anything at surface level. I need to understand the full system before I trust myself to say or build anything.",
    paragraphs: [
      "I started in mechanical engineering, which gave me a seriousness about getting things right, not just getting things to run. The technical answer alone was never the full answer, which is what pulled me toward product design. Design taught me to ask whether the right problem is being solved before solving anything.",
      "At Rotman I went deeper into statistical models, caring about why they broke as much as why they worked. What makes me a capable data scientist is not the breadth of tools I have touched. It is that I approach every problem the way a designer would: starting with the question, not the method.",
      "Outside of the work I dance, mostly classical Indian, plus whatever the kitchen floor allows at midnight. I write in long walks and short notebooks, mostly about cities and rooms and the things people do not say. I keep a steady rotation of music: Begum Akhtar in the morning, Nick Drake in the evening, the Bach Cello Suites whenever I am stuck. I read Mary Oliver and T.S. Eliot to reset my attention, and the Russians on long flights when I want a different century to think in.",
      "I am also the person who builds the alumni system, plans the dinner, and keeps the group chat alive. I came up through student governance and an unusual amount of organising before I came up through models. That has shaped what I think a good data scientist looks like: someone who can hold a room, not only a notebook.",
      "I am choosing to start in data science because it is where the most honest, high stakes problem solving is happening right now. I want to earn the technical depth before I earn the authority to make product decisions on top of it. The sequencing is deliberate.",
    ],
  },

  now: {
    updated: "this week",
    reading: [
      { title: "Inspired", author: "Marty Cagan", note: "rereading the parts on product discovery; what makes a model land in front of a real user." },
      { title: "The Ballad of Never After", author: "Stephanie Garber", note: "the kind of book i save for the train. fairy tale logic, sharper than it looks." },
    ],
    studying: [
      { title: "quant finance", note: "options pricing and asset management. learning to read the math the way traders read it, not the way textbooks present it." },
      { title: "MLOps", note: "specifically, deploying a real app end to end. moving from notebooks to something with a uptime expectation." },
    ],
    listening: ["Begum Akhtar", "Nick Drake", "Bach Cello Suites", "Arooj Aftab"],
    thinking: "what changes when a model has to defend its answer to the person it affected. most of my projects keep ending up here.",
  },


  education: [
    { year: "2026", school: "University of Toronto", program: "Rotman School of Management — Master of Management Analytics" },
    { year: "2025", school: "IIIT Design & Manufacturing Kancheepuram", program: "B.Tech, Mechanical Engineering · Minor in Product Design" },
  ],

  achievements: [
    "1st Place — Koru Problem Hunt, 2025",
    "1st Place — Rotman MMA Datathon, 2026",
    "Finals (Top 7 / 43) — Rotman Design Challenge, 2026",
    "Founded Alumni Association & Alumni Office at IIITDM (1,270+ records, 350 → 550 attendees)",
    "AWS ML Engineer Associate — in progress",
  ],
};
