/* global window */
// Portfolio content — extracted from Experience.docx and Personality.docx
window.PORTFOLIO = {
  owner: {
    name: "Sanjana Kanchibotla",
    initials: "SK",
    role: "Data Scientist · Product Thinker",
    location: "Toronto, ON",
    email: "sanjanakanchibotla@gmail.com",
    links: {
      github: "https://github.com/sanjxksl",
      linkedin: "https://linkedin.com/in/sanjanaksl",
    },
    tagline: "I find the problems worth solving, then use whatever it takes to solve them.",
  },

  folders: [
    { id: "work", name: "Work", kind: "folder" },
    { id: "projects", name: "Projects", kind: "folder" },
    { id: "competitions", name: "Competitions", kind: "folder" },
    { id: "about", name: "About_Me", kind: "folder" },
  ],

  work: [
    {
      id: "cibc",
      name: "CIBC,AI Solutions",
      type: "EXP",
      date: "Jan 2026,Present",
      role: "Global Methodology Programs & Strategy",
      location: "Toronto, Canada",
      kicker: "Current · Finance · Enterprise AI",
      title: "AI-driven exam-scoping assistant for <em>AML examiners</em>",
      subtitle: "Agent + RAG + LLM insight layer, embedded with the CEEP team.",
      body: [
        { h: "Context", p: "Enterprise AML and Compliance exams are fast-paced, high-stakes, and run on confidential, unstructured data scattered across multiple repositories. Examiners lose days understanding prior scopes, locating the right document versions, and identifying coverage gaps." },
        { h: "Approach", p: "Spent two weeks embedded with the team,interviews, ethnographic observation, prioritising real pain points before proposing a solution. Scoped a proactive AI agent that doubles as a centralised repository and smart search engine." },
        { h: "What it does", list: [
          "From a line of business or tentative scope element, retrieves the most relevant documents ranked by relevance,plus templates, prior issues, risk ratings, and emerging insights driven by news and recent changes.",
          "Inline chatbot for document-specific Q&A so examiners don't hunt through huge reports.",
          "RAG over historical exam reports with a roadmap to wire Databricks for automated ingestion and a second LLM trained on domain news for a proactive insight layer.",
        ]},
        { h: "Craft", p: "Deployed in Streamlit with an examiner-friendly configuration UI. Managed version control via GitHub for traceability across model, data, and UI changes. Defined a future evaluation framework using simulated, real-life-inspired case scenarios for continuous quality improvement." },
      ],
      tags: ["RAG", "LLM", "Python", "FinTech", "Databricks"],
      metrics: [
        { v: "2 wks", l: "embedded research" },
        { v: "100+", l: "annual reviews scoped" },
        { v: "~0", l: "to near-instant retrieval" },
      ],
    },
  ],

  projects: [
    {
      id: "exec-anomaly",
      name: "executive_compensation.sql",
      type: "SQL",
      date: "2026",
      kicker: "Financial Analytics, SQL, Risk Scoring, Visualisation",
      title: "Executive compensation <em>anomaly detection</em>",
      subtitle: "Thirty years of Compustat WRDS data, asked a forensic finance question.",
      links: {
        github: "https://github.com/sanjxksl/executive-compensation-anomaly",
        tableau: "https://public.tableau.com/views/ExecutiveCompensationAnomalyDetection/Dashboard1",
      },
      tableauPath: "ExecutiveCompensationAnomalyDetection/Dashboard1",
      body: [
        { p: "Are North American executives being paid anomalously relative to their industry peers, and does company performance justify it. The question is forensic finance dressed as a data engineering problem." },
        { h: "Architecture", p: "An end-to-end anomaly detection system on Compustat WRDS data covering thirty years of executive compensation across North American public companies. The SQL was structured modularly: views instead of repeated subquery joins, a self-join to compute industry-level baselines, and a three-table join across Execucomp, Fundamentals Annual, and Total Q to layer revenue, net income, EBITDA, and Tobin's Q against every flagged executive." },
        { h: "Method", p: "Anomalies were flagged using z-score thresholds relative to industry peers rather than absolute pay. The more important methodological decision was the composite risk metric: anomaly rate multiplied by average severity, adapted from the actuarial Expected Loss framework. This prevents the obvious trap of concluding that large industries like Regional Banks are structurally worse than smaller ones simply because they have more observations." },
        { h: "What the data said", p: "The industries with the highest raw anomaly counts were not the most structurally problematic once normalised. Forest Products, Brewers, and Industrial Gases had the highest composite scores. Systems Software and Industrial REITs had the most extreme individual anomalies despite lower frequency." },
        { h: "Counterintuitive finding", p: "Anomaly count grew steadily from 1992 to 2008, but average severity declined over the same period. Governance reforms appear to have moderated the degree of excess even as the number of anomalous pay packages increased." },
      ],
      tags: ["SQL", "Financial Analytics", "Risk Scoring", "Tableau", "WRDS"],
      metrics: [
        { v: "30 yrs", l: "Compustat coverage" },
        { v: "3", l: "tables joined" },
        { v: "1992", l: "to 2008 trend" },
      ],
    },
    {
      id: "pead",
      name: "pead_replication.py",
      type: "FIN",
      date: "2026",
      kicker: "Empirical Finance, Asset Pricing, Statistical Modelling, WRDS",
      title: "Post-earnings announcement drift <em>replication</em>",
      subtitle: "Ball and Brown (1968) on twenty-three years of modern data.",
      links: {
        github: "https://github.com/sanjxksl/PEAD",
      },
      body: [
        { p: "Does the market underreact to earnings news, and does that underreaction persist long enough to be systematically exploitable. Ball and Brown showed it in 1968. This replication asks whether it still holds on twenty-three years of modern data." },
        { h: "Construction", p: "A full replication on CRSP and Compustat data from 2000 to 2023. Standardised Unexpected Earnings were constructed using an eight-quarter rolling volatility window. SUE deciles were assigned from prior-quarter breakpoints rather than current-quarter, which prevents the lookahead bias that invalidates many replications of this kind." },
        { h: "Pipeline", p: "CRSP and Compustat were linked via the CCM merge table. Size-adjusted abnormal returns were computed using Fama-French NYSE breakpoints. An event-time return panel was built to track cumulative abnormal returns across a twelve-month post-announcement window by SUE decile." },
        { h: "What the regressions said", p: "Cross-sectional regressions with HC1 standard errors confirmed that PEAD concentrates in small firms, consistent with the Shleifer-Vishny limits-to-arbitrage view: arbitrage is costly and risky in small caps, so mispricing persists. A secular attenuation in the top-bottom spread over the sample period is consistent with algorithmic trading accelerating price discovery." },
      ],
      tags: ["Empirical Finance", "Asset Pricing", "Python", "WRDS", "CRSP"],
      metrics: [
        { v: "23 yrs", l: "2000 to 2023" },
        { v: "10", l: "SUE deciles" },
        { v: "12 mo", l: "event window" },
      ],
    },
    {
      id: "esg-returns",
      name: "esg_returns.py",
      type: "FIN",
      date: "2026",
      kicker: "Empirical Finance, ESG Analytics, Regression",
      title: "ESG performance and <em>financial returns</em>",
      subtitle: "Twenty thousand firm-years on whether ESG predicts anything earnings does not.",
      links: {
        github: "https://github.com/sanjxksl/esg-returns-study",
      },
      body: [
        { p: "Does ESG performance predict financial returns, or is any observed relationship a proxy for the fundamentals investors already price." },
        { h: "Sample", p: "A co-authored study on 20,764 firm-year observations across 3,351 US firms from 2013 to 2023, using LSEG Refinitiv ESG scores, Compustat, and CRSP. Led Part II on the determinants of ESG performance." },
        { h: "Specifications", p: "Four OLS models with firm-level controls and Fama-French 48 industry fixed effects. Two findings are worth highlighting for their methodological honesty. First, the positive leverage to ESG association found in naive models collapsed entirely once industry composition was controlled for. The relationship was an industry composition artefact. Second, R&D intensity reversed sign within industries relative to the unconditional estimate, a classic Simpson's paradox pattern." },
        { h: "Central finding", p: "ESG predicts next-year ROA positively and significantly after controls, but the return signal disappears once earnings news enters the model. The market prices ESG through fundamentals, not as a standalone factor. ESG is not alpha. It is a signal that gets absorbed by what it predicts." },
      ],
      tags: ["Empirical Finance", "ESG", "Regression", "WRDS"],
      metrics: [
        { v: "20,764", l: "firm-years" },
        { v: "3,351", l: "US firms" },
        { v: "4", l: "OLS specifications" },
      ],
    },
    {
      id: "credit-risk",
      name: "credit_risk.py",
      type: "ML",
      date: "2025",
      kicker: "Financial ML, Explainable AI, MLOps, AWS SageMaker",
      title: "Credit risk with <em>counterfactual explanations</em>",
      subtitle: "Predict default accurately and tell rejected applicants what would change the outcome.",
      links: {
        github: "https://github.com/sanjxksl/credit-risk-counterfactual",
      },
      body: [
        { p: "Can a credit risk model not only predict default accurately but also tell a declined applicant what specifically would need to change for an approval, without encoding demographic bias." },
        { h: "Models", p: "An end-to-end credit risk classification system on 148,670 mortgage applications. Two models were trained, an MLP and XGBoost, achieving AUC-ROC of 0.901 with a calibration gap under 0.3% using Platt scaling." },
        { h: "Where the work actually sat", p: "Most of the intellectual effort lived before any modelling began. A systematic categorical feature audit caught that credit_type's apparent predictive power came entirely from one bureau category, EQUI, which showed a 100% default rate across 15,000 cases. This signals an unobserved loan programme, not a genuine borrower risk signal. Five such artefact features were removed before training. A model trained on those features would have shown good in-sample performance and failed entirely on new originator programmes." },
        { h: "Counterfactuals as product", p: "DiCE counterfactual explanations identify the minimum loan structure changes needed to flip a predicted default. Counterfactual generation failures were treated as signal rather than noise: when no feasible restructuring exists, it means the risk is driven by immutable characteristics rather than adjustable loan terms." },
        { h: "Fairness and deployment", p: "A fairness audit across gender, age, and geography returned a disparate impact ratio of 1.021, passing the 80% rule. The inference pipeline exactly replicates the training preprocessing chain, log transforms before standardisation, winsorisation, one-hot encoding, preventing training-serving skew. Deployed as a FastAPI endpoint on SageMaker with a custom Docker container and an Evidently monitoring layer that triggers retraining when feature drift exceeds 30% or the predicted default rate shifts more than 5 percentage points." },
      ],
      tags: ["PyTorch", "XGBoost", "Explainable AI", "AWS SageMaker", "FinTech"],
      metrics: [
        { v: "0.901", l: "AUC-ROC" },
        { v: "1.021", l: "DIR, fairness" },
        { v: "100%", l: "counterfactual success" },
      ],
    },
    {
      id: "aesthify",
      name: "aesthify.py",
      type: "CV",
      date: "2025",
      kicker: "Computer Vision, Product Design, Design Research",
      title: "Aesthify, quantifying <em>subjective taste</em>",
      subtitle: "Rule-based design scores against what 101 people actually preferred.",
      links: {
        github: "https://github.com/sanjxksl/Aesthify",
      },
      body: [
        { p: "Can visual design principles be measured objectively, and does what a computer calculates as good design match what people actually prefer." },
        { h: "Pipeline", p: "A Flask web application that runs a computer vision pipeline on interior layout images and scores them across seven design principles: balance, proportion, symmetry, simplicity, harmony, contrast, and unity. YOLOv8 object detection and Roboflow were used to identify objects. Rule-based scoring computed the principle scores from those detections." },
        { h: "Validation", p: "The computed scores were validated against a 101-participant user study collecting aesthetic ratings on the same images. Correlation analysis compared machine scores against human preference. Demographic clustering identified whether perception patterns varied by geography and background." },
        { h: "Findings", list: [
          "Simplicity correlated most strongly with user preference (r = 0.68).",
          "Symmetry was negatively correlated (r = -0.60). People preferred asymmetric layouts.",
          "Aesthetic judgment varied significantly across demographic groups.",
        ]},
        { p: "The point is not that design can be reduced to a formula. The point is that it cannot, and this study makes that measurable." },
      ],
      tags: ["Computer Vision", "Python", "Design Research"],
      metrics: [
        { v: "101", l: "participants" },
        { v: "0.68", l: "simplicity correlation" },
        { v: "7", l: "principles scored" },
      ],
    },
    {
      id: "evidence-engine",
      name: "evidence_engine.py",
      type: "AI",
      date: "2025",
      kicker: "AI Tooling, Product Management, Cognitive Bias",
      title: "Evidence Engine for <em>product decisions</em>",
      subtitle: "Help product managers synthesise messy research into structured, defensible insights.",
      links: {
        github: "https://github.com/sanjxksl/evidence-engine",
      },
      body: [
        { p: "Prioritisation frameworks like RICE get gamed because the inputs, the evidence, are never rigorously gathered or challenged before scoring begins. What if the tool forced that rigour." },
        { h: "Architecture", p: "A conversational AI tool built in Streamlit using the Gemini API, designed for product managers synthesising research into structured, defensible insights. The architecture is modular: evidence extractor, synthesiser, intent classifier, output generator, reasoning tracer, and SQLite persistence layer." },
        { h: "Modes", p: "LLM-based intent classification routes queries across five modes: hypothesis testing, pattern identification, confidence assessment, stakeholder reporting, and assumption validation. Every verdict comes with a transparent reasoning trace that classifies the supporting and counter-evidence into six types: user quotes, behavioural observations, support tickets, analytics data, stakeholder input, and competitor intelligence." },
        { h: "Foundation", p: "The design is grounded in a literature review on HiPPO bias, confirmation bias, and anchoring from Kahneman-Tversky and Morewedge et al., and validated through interviews with practising PMs before any code was written." },
      ],
      tags: ["LLM", "Streamlit", "Gemini", "Product Tooling"],
      metrics: [
        { v: "5", l: "intent modes" },
        { v: "6", l: "evidence types" },
        { v: "4", l: "PMs interviewed" },
      ],
    },
    {
      id: "us-income",
      name: "us_income.py",
      type: "DL",
      date: "2025",
      kicker: "Coursework, Deep Learning",
      title: "US Census income prediction",
      subtitle: "A reliable neural network on imbalanced tabular data where naive approaches fail.",
      coursework: true,
      links: {
        github: "https://github.com/sanjxksl/us-income-prediction",
      },
      body: [
        { p: "Binary income classification, above or below $50K annually, on the US Census dataset. Class split 75 to 25, with 90 features after preprocessing." },
        { h: "Preprocessing", p: "Median imputation for numeric features, most-frequent imputation for categorical features, MinMaxScaler normalisation (preferred over StandardScaler after observing a 2% accuracy gain), one-hot encoding via ColumnTransformer." },
        { h: "Feature engineering", p: "gain_loss_ratio = (capital-gain + 1) divided by (capital-loss + 1). total_capital = capital-gain minus capital-loss. Empirically validated that adding more than two engineered features decreased performance." },
        { h: "Model", p: "Two-hidden-layer neural network ([256, 128] units) with ReLU, BatchNorm, and dropout 0.3. Adam optimiser, learning rate 0.001. Deeper architectures (four-plus layers, [512, 256, 128, 64]) degraded accuracy to 82 to 83% due to noise amplification on tabular data." },
        { h: "Training and threshold", p: "Five-fold stratified cross-validation ensemble. Class weight 1.2 for the minority high-earner class. Early stopping with patience 15, ReduceLROnPlateau, batch size 64, max 100 epochs. Classification threshold optimised from 0.5 to 0.70 to reduce false positives." },
        { h: "Result", p: "85.62% accuracy, 0.9094 AUC-ROC, 0.6980 F1. Competitive with XGBoost (86 to 87%) while showing neural network applicability to tabular income data." },
      ],
      tags: ["Deep Learning", "Keras", "Coursework"],
      metrics: [
        { v: "85.6%", l: "accuracy" },
        { v: "0.91", l: "AUC-ROC" },
        { v: "5", l: "fold ensemble" },
      ],
    },
    {
      id: "alumni-career",
      name: "alumni_career.py",
      type: "DS",
      date: "2025",
      kicker: "Coursework, Predictive Analytics",
      title: "Alumni career success prediction",
      subtitle: "Scattered, inconsistent institutional data made into one analysis-ready view.",
      coursework: true,
      links: {
        github: "https://github.com/sanjxksl/alumni-career-success",
      },
      body: [
        { p: "Predict salary and career outcomes for IIITDM alumni given role and location. The institutional problem is scattered, inconsistent alumni data that cannot be used for curriculum decisions or outcome reporting." },
        { h: "Data preparation", p: "Merged four fragmented alumni CSV datasets with heterogeneous salary formats: USD, INR, lakhs per annum, monthly figures. Built a pipeline to standardise, convert, and unify records into a single analysis-ready dataset." },
        { h: "Features", p: "Unified designation and country-of-employment columns. Log transformation on salary. One-hot encoding for categorical features. StandardScaler normalisation." },
        { h: "Models", p: "Random Forest Regressor for salary prediction with GridSearchCV and 5-fold cross-validation, evaluated using MAE and R-squared. Random Forest Classifier for binary career success classification (above or below median salary), with balanced class weights and evaluation across accuracy, ROC-AUC, confusion matrix, and precision-recall." },
        { h: "Interface", p: "Built an interactive command-line prediction interface allowing salary and career success prediction for arbitrary designation and country inputs." },
      ],
      tags: ["Random Forest", "Python", "Coursework"],
      metrics: [
        { v: "4", l: "datasets merged" },
        { v: "2", l: "models" },
      ],
    },
  ],

  competitions: [
    {
      id: "koru",
      name: "koru_thirdplace.md",
      type: "CASE",
      date: "Nov 2025",
      kicker: "Finalist, Koru Problem Hunt",
      title: "Koru Problem Hunt, <em>ThirdPlace</em>",
      subtitle: "Mixed-methods research, a dual-sided marketplace, and the friction trinity.",
      body: [
        { h: "Outcome", p: "Finalist. Designed ThirdPlace, a dual-sided social marketplace for hobby studios and hobbyists built on a credit-based subscription model. Identified a white space no competitor occupied." },
        { h: "Problem", p: "Hobby participation has three dominant barriers: cost (82%), schedule fit (84%), and discovery (90%). Studios lose an average of $300 per unfilled 10-person ceramics class and operate at 51% average capacity. No existing platform addresses both sides of that equation simultaneously." },
        { h: "Research", p: "Mixed-methods. A quantitative survey (79% aged 18 to 24, equal gender split, 71% with prior hobby class experience) and eight in-depth thirty-minute interviews across hobbyists and studio owners. The survey quantified the friction trinity. The interviews surfaced what studios actually feared: commission structure, trial conversion, demographic fit. And what they actually wanted: booking automation, new member acquisition, revenue predictability." },
        { h: "Segmentation", p: "The hobbyist market split into two behavioural profiles. Explorers, variety-seekers blocked by schedule. Connectors, community-builders blocked by upfront commitment. Connectors were recommended as the initial target segment based on retention potential." },
        { h: "Product", p: "ThirdPlace combined consolidated discovery, a social experience layer with group bookings and gamification, and tiered credit-based pricing (8, 16, and 32-credit monthly plans with rollover). Studios retain full pricing control. Commission is fixed and transparent, below Groupon's 50%. A hypothesis register was built across desirability, feasibility, and viability, with each assumption assigned a risk level and a specific experiment design." },
        { h: "Sizing", p: "TAM $45B+, SAM $3.6B, SOM $9 to 15M over three years." },
      ],
      tags: ["Product Strategy", "Mixed-Methods Research", "Consumer Tech"],
      metrics: [
        { v: "82%", l: "cost barrier" },
        { v: "84%", l: "schedule barrier" },
        { v: "90%", l: "discovery barrier" },
      ],
    },
    {
      id: "mma",
      name: "mma_datathon.md",
      type: "CASE",
      date: "Jan 2026",
      kicker: "1st place, Rotman MMA Datathon",
      title: "Rotman MMA Datathon",
      subtitle: "Six thousand hours of web traffic, causal inference, and a budget reallocation.",
      body: [
        { h: "Outcome", p: "First place out of all participating teams, Rotman MMA Datathon, January 2026." },
        { h: "Problem", p: "A retail brand operating across Canada and the US wanted to evaluate paid search campaign effectiveness. The naive approach, correlating ad spend with traffic, would have given the wrong answer. Organic and paid traffic move together for reasons that have nothing to do with the campaign." },
        { h: "Method", p: "Causal inference applied to 6,865 hours of web traffic data to isolate true campaign impact from organic baseline. The separation of signal from correlation is where most teams fail on real-world data of this kind." },
        { h: "Findings", p: "35% positive ROI in the US, loss-making spend in Canada. Recommendation: reallocate $75,000 to $90,000 in paid search budget from Canada to the US markets. The recommendation was specific enough to act on the next day." },
      ],
      tags: ["Causal Inference", "Marketing Analytics", "Python"],
      metrics: [
        { v: "1st", l: "of all teams" },
        { v: "+35%", l: "US ROI" },
        { v: "$75-90K", l: "reallocation" },
      ],
    },
    {
      id: "rdc",
      name: "rdc_compass.md",
      type: "CASE",
      date: "Mar 2026",
      kicker: "Finalist (top 7 of 43), Rotman Design Challenge",
      title: "Rotman Design Challenge, <em>Compass</em>",
      subtitle: "Designed an LLM agent inside Manulife's app for the health-wealth feedback loop.",
      body: [
        { h: "Outcome", p: "Finalist, top 7 of 43 teams, Rotman Design Challenge 2026. Designed for Manulife." },
        { h: "Problem", p: "73% of users leave health benefits unused. Not because the products are bad, but because the system is impossible to navigate. The problem is navigability failure, not product failure. That distinction changes everything about what the solution needs to be." },
        { h: "Research", p: "Seven empathy interviews and 38 survey responses revealed a health-wealth feedback loop. People who cannot access their benefits incur out-of-pocket costs that compound over time. The research identified three failure modes: users do not know what they have, cannot find it when they need it, and are not reminded at the moments it matters most." },
        { h: "Product", p: "Compass, an LLM-powered AI agent embedded in Manulife's existing app, integrating data across Group Benefits, Vitality, and Individual Insurance. Three-layer architecture: a conversational LLM interface, smart data retrieval trained on domain-specific insurance data, and an event-trigger engine that responds to life signals (job change, new dependent, policy renewal). The trigger engine is the differentiating layer. It surfaces relevant coverage at the exact life moment when a user would otherwise miss it." },
        { h: "Validation", p: "87% of users said they would use the tool to find unused benefits, 79% to understand coverage, 62% rated usefulness 7 to 10 out of 10." },
      ],
      tags: ["FinTech", "Product Design", "LLM Architecture", "User Research"],
      metrics: [
        { v: "73%", l: "benefits unused" },
        { v: "87%", l: "would adopt" },
        { v: "7/43", l: "finalists" },
      ],
    },
  ],

  learning: [
    { hash: "a1f9d02", date: "2026·Q2", branch: "QUANT FINANCE",
      msg: "Studying options pricing and asset pricing theory",
      desc: "Working through quantitative finance: options, derivatives, and asset pricing models. Building the theoretical layer underneath the empirical work done in PEAD and ESG.",
      current: true },
    { hash: "b3c1e77", date: "2026·Q2", branch: "MLOPS",
      msg: "Rebuilding credit risk model for production",
      desc: "Revisiting the credit risk counterfactual project from 2025. Hardening the inference pipeline, deployment architecture, and monitoring layer to production standard on SageMaker." },
    { hash: "7a2c19f", date: "2026·Q2", branch: "PRODUCT",
      msg: "Compass,LLM agent for Manulife (RDC finals)",
      desc: "Three-layer architecture with event triggers on life signals. The health-wealth feedback loop is real and measurable. Top 7 of 43 teams, Rotman Design Challenge 2026." },
    { hash: "d8a04bc", date: "2026·Q1", branch: "EMPIRICAL FINANCE",
      msg: "PEAD replication and ESG returns study",
      desc: "Ball and Brown (1968) on CRSP/Compustat. Then co-authored an ESG study across 20,764 firm-years. The return signal collapses once earnings news enters the model. The market prices ESG through fundamentals." },
    { hash: "e4f1b03", date: "2026·Q1", branch: "RAG / LLM",
      msg: "CIBC: embedded fieldwork then RAG agent for AML scoping",
      desc: "Two weeks of ethnographic observation before any architecture decision. Built a RAG-based exam-scoping assistant with a Streamlit UI and Databricks roadmap. Deepening LLM application design through the Stripe RAG agent project and a dedicated course alongside." },
    { hash: "c9a7d51", date: "2026·Q1", branch: "CAUSAL INFERENCE",
      msg: "1st place,MMA Datathon",
      desc: "Causal inference on paid-search web traffic. Learned to separate signal from correlation before recommending a $75-90K spend shift across Canada and the US markets." },
  ],

  gallery: [
    'Celebrating our contribution to Rotman as Ambassadors',
    'Presenting at the Rotman Datathon 2026 finals',
    'Orientation for Rotman\'s Master of Management Analytics',
    'Presenting at the Manulife RDC Case Competition finals',
    'First place at the Datathon Prize Ceremony',
    'Presenting at the Koru Case Competition finals',
    'Design for Future workshop with students from across North America',
    'Showcasing our work at CIBC to the Rotman panel',
  ],

  personality: {
    quote: "I cannot engage with anything at surface level. I need to understand the full system before I trust myself to say or build anything.",
    paragraphs: [
      "What genuinely excites me is problem solving. I love playing with data, building models, testing hypotheses, and seeing where the conclusions land.",
      "Through engineering, product design, and now analytics at Rotman, I have deliberately built a toolkit,user empathy, statistical modelling, ML, financial data analysis,because I want to be able to solve these kinds of problems. Especially the ones where the deeper you go, the stronger the signal gets. And, that is where my passion lives.",
      "Apart from work, I love to write and I have been a dancer. Fun Fact: The first time I performed on stage was when I was 5. I love Linkin Park and I listen to a lot of Indian niche r&b and hip hop artists. I tend to always find new hobbies to keep life exciting and the most recent one is baking!",
    ],
  },

  now: {
    updated: "this week",
    reading: [
      { title: "Inspired", author: "Marty Cagan", note: "rereading the parts on product discovery; what makes a model land in front of a real user." },
      { title: "The Ballad of Never After", author: "Stephanie Garber", note: "the kind of book i save for the train. fairy tale logic, sharper than it looks." },
    ],
    studying: [
      { title: "quant finance", note: "options pricing and asset management. learning to read the math the way traders read it, not the way textbooks present it." },
      { title: "MLOps", note: "specifically, deploying a real app end to end. moving from notebooks to something with a uptime expectation." },
    ],
    listening: ["Chaar Diwari", "Mokita", "Sabrina Carpenter"],
    thinking: "what changes when a model has to defend its answer to the person it affected. most of my projects keep ending up here.",
  },


  education: [
    { year: "2026", school: "University of Toronto", program: "Rotman School of Management,Master of Management Analytics" },
    { year: "2025", school: "IIIT Design & Manufacturing Kancheepuram", program: "B.Tech, Mechanical Engineering · Minor in Product Design" },
  ],

  achievements: [
    "1st Place,Koru Problem Hunt, 2025",
    "1st Place,Rotman MMA Datathon, 2026",
    "Finals (Top 7 / 43),Rotman Design Challenge, 2026",
    "Founded Alumni Association & Alumni Office at IIITDM (1,270+ records, 350 to 550 attendees)",
    "AWS ML Engineer Associate,in progress",
  ],
};
