/* global window */
// Portfolio content — extracted from Experience.docx and Personality.docx
window.PORTFOLIO = {
  owner: {
    name: "Sanjana Kanchibotla",
    initials: "SK",
    role: "Data Scientist · Product Thinker",
    location: "Toronto, ON",
    email: "sanjanakanchibotla@gmail.com",
    links: {
      github: "https://github.com/sanjxksl",
      linkedin: "https://linkedin.com/in/sanjanaksl",
    },
    tagline: "I find the problems worth solving, then use whatever it takes to solve them.",
  },

  folders: [
    { id: "work", name: "Work", kind: "folder" },
    { id: "projects", name: "Projects", kind: "folder" },
    { id: "competitions", name: "Competitions", kind: "folder" },
    { id: "about", name: "About_Me", kind: "folder" },
  ],

  work: [
    {
      id: "cibc",
      name: "CIBC,AI Solutions",
      type: "EXP",
      date: "Jan 2026,Present",
      role: "Global Methodology Programs & Strategy",
      location: "Toronto, Canada",
      kicker: "Current · Finance · Enterprise AI",
      title: "AI-driven exam-scoping assistant for <em>AML examiners</em>",
      subtitle: "An AI agent that acts as both a smart search engine and knowledge base — built for the CEEP compliance team.",
      arch: ["Exam Documents", "RAG Chunking", "Vector Search", "LLM Generation", "Examiner Interface"],
      body: [
        { h: "The Problem", p: "Compliance examiners spend days — before any actual review work starts — searching through scattered documents to understand what was examined before, what was missed, and where to focus next. The information exists, but there's no easy way to surface the right piece at the right moment." },
        { h: "How I Approached It", p: "Spent two weeks embedded with the team — sitting with examiners, observing their workflow, and asking what actually slows them down — before writing a single line of code. The goal was to understand the real pain, not build a solution looking for a problem." },
        { h: "What It Does", list: [
          "Give it a line of business or a scope element, and it surfaces the most relevant prior documents — ranked by relevance — along with templates, past issues, and risk signals drawn from recent news and regulatory changes.",
          "An inline chat interface lets examiners ask questions directly about any document without hunting through it manually.",
          "Built on a retrieval-augmented generation (RAG) architecture, with a roadmap to connect Databricks for automated data ingestion and a second AI layer trained on domain-specific news for proactive insights.",
        ]},
        { h: "What I Built", p: "A clean, examiner-friendly interface in Streamlit. Version-controlled through GitHub so every model, data, and interface change is traceable. Designed a testing framework using realistic exam scenarios so the system can be evaluated and improved continuously." },
      ],
      tags: ["RAG", "LLM", "Python", "FinTech", "Databricks"],
      metrics: [
        { v: "2 wks", l: "embedded fieldwork" },
        { v: "100+", l: "annual reviews scoped" },
        { v: "~0", l: "to near-instant retrieval" },
      ],
    },
  ],

  projects: [
    {
      id: "exec-anomaly",
      name: "executive_compensation.sql",
      type: "SQL",
      date: "2026",
      kicker: "Financial Analytics, SQL, Risk Scoring, Visualisation",
      title: "Executive compensation <em>anomaly detection</em>",
      subtitle: "Thirty years of data, one forensic finance question: are executives being paid out of line with their peers?",
      links: {
        github: "https://github.com/sanjxksl/executive-compensation-anomaly",
        tableau: "https://public.tableau.com/views/ExecutiveCompensationAnomalyDetection/Dashboard1",
      },
      tableauPath: "ExecutiveCompensationAnomalyDetection/Dashboard1",
      arch: ["Compustat WRDS (30yr)", "SQL Modular Views", "Industry Peer Baseline", "Anomaly Scoring", "Tableau Dashboard"],
      body: [
        { p: "Are North American executives being paid unusually compared to their industry peers — and does their company's performance justify it? This is a forensic finance question dressed as a data problem." },
        { h: "How It Works", p: "An end-to-end anomaly detection system built on thirty years of executive compensation data. The SQL is structured in clean, reusable layers: industry peer groups are built through a self-join, then each flagged executive is measured against their company's actual revenue, profit, and growth performance." },
        { h: "Why The Method Matters", p: "Anomalies are flagged relative to industry peers — not absolute pay levels — so a $10M package in pharma is measured differently than one in regional banking. The composite risk score combines how often anomalies appear with how severe they are, adapted from actuarial risk modelling, so larger industries aren't penalised just for having more data." },
        { h: "What the Data Said", p: "The industries with the most anomalies weren't the most structurally problematic once adjusted for size. Forest Products, Brewers, and Industrial Gases had the highest composite risk scores. Systems Software and Industrial REITs had the most extreme individual cases despite lower overall frequency." },
        { h: "The Counterintuitive Finding", p: "Anomaly counts rose steadily from 1992 to 2008, but the average severity actually declined. Governance reforms appear to have moderated how extreme the excess gets, even as the number of anomalous pay packages increased." },
      ],
      tags: ["SQL", "Financial Analytics", "Risk Scoring", "Tableau", "WRDS"],
      metrics: [
        { v: "30 yrs", l: "Compustat coverage" },
        { v: "3", l: "data tables joined" },
        { v: "1992–2008", l: "trend analysed" },
      ],
    },
    {
      id: "pead",
      name: "pead_replication.py",
      type: "FIN",
      date: "2026",
      kicker: "Empirical Finance, Asset Pricing, Statistical Modelling, WRDS",
      title: "Post-earnings announcement drift <em>replication</em>",
      subtitle: "Ball and Brown (1968) on twenty-three years of modern data.",
      links: {
        github: "https://github.com/sanjxksl/PEAD",
      },
      arch: ["CRSP + Compustat", "CCM Merge", "SUE Decile Construction", "Event-Time Return Panel", "Cross-Section Regressions"],
      body: [
        { p: "When a company reports earnings that beat expectations, its stock tends to keep rising for months afterwards. Ball and Brown showed this in 1968. This replication asks whether it still holds on twenty-three years of modern data — and why." },
        { h: "What Was Built", p: "A full replication on stock and accounting data from 2000 to 2023. Earnings surprises were constructed using a rolling historical window — critically, using prior-quarter benchmarks rather than current-quarter ones, which prevents a common error in studies of this kind where future information leaks into the analysis." },
        { h: "What the Analysis Found", p: "The drift concentrates in smaller companies, consistent with a well-known theory: it's costly and risky to bet against a misprice in small stocks, so inefficiencies persist longer. The gap between the highest and lowest earnings-surprise groups has narrowed over the sample period, consistent with algorithmic trading speeding up how quickly markets process news." },
      ],
      tags: ["Empirical Finance", "Asset Pricing", "Python", "WRDS", "CRSP"],
      metrics: [
        { v: "23 yrs", l: "2000 to 2023" },
        { v: "10", l: "earnings surprise deciles" },
        { v: "12 mo", l: "post-event window" },
      ],
    },
    {
      id: "esg-returns",
      name: "esg_returns.py",
      type: "FIN",
      date: "2026",
      kicker: "Empirical Finance, ESG Analytics, Regression",
      title: "ESG performance and <em>financial returns</em>",
      subtitle: "Twenty thousand firm-years on whether ESG predicts anything that earnings don't already.",
      links: {
        github: "https://github.com/sanjxksl/esg-returns-study",
      },
      arch: ["LSEG ESG Scores + CRSP + Compustat", "Panel Data Construction", "OLS Regression Models", "Industry Fixed Effects", "Return Signal Test"],
      body: [
        { p: "Does ESG performance predict financial returns — or is any observed relationship really just a reflection of factors investors already price in?" },
        { h: "The Study", p: "A co-authored analysis of 20,764 firm-year observations across 3,351 US companies from 2013 to 2023, combining ESG ratings from LSEG Refinitiv with financial data from Compustat and CRSP. I led the section on what drives ESG performance itself." },
        { h: "Two Findings Worth Highlighting", p: "First, a relationship between leverage and ESG that appeared in early models vanished entirely once we controlled for industry. It was an industry composition effect, not a real signal. Second, R&D intensity reversed direction within industries compared to the overall average — a textbook Simpson's paradox, where looking at the full picture hides what's actually happening within groups." },
        { h: "The Central Finding", p: "ESG positively predicts next-year profitability after controlling for other factors. But the stock return signal disappears once earnings news enters the model. The market prices ESG through fundamentals — not as a standalone factor. ESG is not a source of excess return. It's a signal that gets absorbed by what it's actually predicting." },
      ],
      tags: ["Empirical Finance", "ESG", "Regression", "WRDS"],
      metrics: [
        { v: "20,764", l: "firm-years analysed" },
        { v: "3,351", l: "US firms" },
        { v: "4", l: "regression models" },
      ],
    },
    {
      id: "credit-risk",
      name: "credit_risk.py",
      type: "ML",
      date: "2025",
      kicker: "Financial ML, Explainable AI, MLOps, AWS SageMaker",
      title: "Credit risk with <em>counterfactual explanations</em>",
      subtitle: "Predict default accurately — and tell rejected applicants exactly what would change the outcome.",
      links: {
        github: "https://github.com/sanjxksl/credit-risk-counterfactual",
      },
      arch: ["148K Mortgage Applications", "Feature Audit + Cleaning", "MLP + XGBoost", "DiCE Counterfactuals", "FastAPI on SageMaker"],
      body: [
        { p: "Can a credit risk model not only predict default accurately, but also explain to a declined applicant what would specifically need to change for an approval — without encoding demographic bias?" },
        { h: "The Models", p: "Two models were trained on 148,670 mortgage applications — a neural network and XGBoost — achieving strong predictive accuracy (AUC-ROC of 0.901) with well-calibrated probability outputs." },
        { h: "Where the Real Work Happened", p: "Most of the effort came before any modelling. A careful audit of the input features uncovered that one variable appeared highly predictive only because a single category within it showed a 100% default rate across 15,000 cases — a sign of an unobserved loan programme, not genuine borrower risk. Five such features were removed before training. A model built on those features would have looked accurate in testing and failed on new data." },
        { h: "Counterfactuals as a Feature", p: "After a decline decision, the system generates counterfactual explanations: the minimum changes to loan structure that would flip the prediction to an approval. When no such restructuring is feasible, that's treated as meaningful information — it means the risk is driven by factors that can't be changed, not by adjustable loan terms." },
        { h: "Fairness and Deployment", p: "A fairness audit across gender, age, and geography returned a disparate impact ratio of 1.021, passing the 80% rule. Deployed as a live API endpoint on AWS SageMaker with automated monitoring that triggers retraining when data patterns drift beyond defined thresholds." },
      ],
      tags: ["PyTorch", "XGBoost", "Explainable AI", "AWS SageMaker", "FinTech"],
      metrics: [
        { v: "0.901", l: "AUC-ROC" },
        { v: "1.021", l: "DIR, fairness" },
        { v: "148K", l: "mortgage applications" },
      ],
    },
    {
      id: "aesthify",
      name: "aesthify.py",
      type: "CV",
      date: "2025",
      kicker: "Computer Vision, Product Design, Design Research",
      title: "Aesthify, quantifying <em>subjective taste</em>",
      subtitle: "Rule-based design scores vs. what 101 people actually preferred.",
      links: {
        github: "https://github.com/sanjxksl/Aesthify",
      },
      arch: ["Interior Layout Images", "YOLOv8 Object Detection", "7 Principle Scores", "101-Person Study", "Correlation Analysis"],
      body: [
        { p: "Can visual design principles be measured objectively — and does what a computer calculates as \"good design\" actually match what people prefer?" },
        { h: "How It Works", p: "A web application that analyses interior layout images and scores them across seven design principles: balance, proportion, symmetry, simplicity, harmony, contrast, and unity. Object detection (YOLOv8) identifies what's in the room; rule-based scoring computes each principle from those detections." },
        { h: "The Validation", p: "The computed scores were compared against aesthetic ratings collected from 101 real participants. Demographic clustering checked whether perception patterns differed by geography and background." },
        { h: "What the Study Found", list: [
          "Simplicity correlated most strongly with user preference (r = 0.68).",
          "Symmetry was negatively correlated (r = −0.60). People preferred asymmetric layouts.",
          "Aesthetic judgment varied significantly across demographic groups.",
        ]},
        { p: "The point isn't that design can be reduced to a formula. The point is that it can't — and this study makes that measurable." },
      ],
      tags: ["Computer Vision", "Python", "Design Research"],
      metrics: [
        { v: "101", l: "study participants" },
        { v: "0.68", l: "simplicity correlation" },
        { v: "7", l: "design principles" },
      ],
    },
    {
      id: "evidence-engine",
      name: "evidence_engine.py",
      type: "AI",
      date: "2025",
      kicker: "AI Tooling, Product Management, Cognitive Bias",
      title: "Evidence Engine for <em>product decisions</em>",
      subtitle: "A tool that forces product teams to gather and challenge evidence before scoring a priority.",
      links: {
        github: "https://github.com/sanjxksl/evidence-engine",
      },
      arch: ["User Query", "Intent Classification", "Evidence Extraction", "Synthesis Layer", "Reasoning Trace + Output"],
      body: [
        { p: "Prioritisation frameworks get gamed because the evidence behind the scores is never rigorously gathered or challenged. What if the tool forced that rigour before any scoring began?" },
        { h: "What Was Built", p: "A conversational AI tool built in Streamlit using the Gemini API, designed for product managers synthesising research into structured, defensible decisions. The architecture has six modules: evidence extractor, synthesiser, intent classifier, output generator, reasoning tracer, and a database persistence layer." },
        { h: "How It Works", p: "An AI classifier routes each query to one of five modes: hypothesis testing, pattern identification, confidence assessment, stakeholder reporting, or assumption validation. Every output comes with a transparent reasoning trace that classifies evidence by type — user quotes, behavioural data, support tickets, analytics, stakeholder input, or competitor intelligence." },
        { h: "Why It Was Built This Way", p: "The design is grounded in research on common decision-making biases (the HiPPO effect, confirmation bias, anchoring) and validated through interviews with four practicing product managers before any code was written." },
      ],
      tags: ["LLM", "Streamlit", "Gemini", "Product Tooling"],
      metrics: [
        { v: "5", l: "query modes" },
        { v: "6", l: "evidence types" },
        { v: "4", l: "PMs interviewed" },
      ],
    },
    {
      id: "us-income",
      name: "us_income.py",
      type: "DL",
      date: "2025",
      kicker: "Coursework, Deep Learning",
      title: "US Census income prediction",
      subtitle: "A reliable neural network on imbalanced data, where the naive approach fails.",
      coursework: true,
      links: {
        github: "https://github.com/sanjxksl/us-income-prediction",
      },
      arch: ["Census Data (90 features)", "Preprocessing Pipeline", "2-Layer Neural Network", "Threshold Optimisation", "Income Prediction"],
      body: [
        { p: "Predict whether a person earns above or below $50K annually from US Census data. The class split is 75/25, and naive models optimised for accuracy will simply predict everyone as low-income and look fine on paper." },
        { h: "Key Preprocessing Decisions", p: "MinMaxScaler normalisation was chosen over the more common StandardScaler after a 2% accuracy improvement was observed. Two engineered capital features were added — more than two decreased performance, a finding that held consistently across cross-validation folds." },
        { h: "Model and Training", p: "A two-hidden-layer neural network trained with 5-fold cross-validation. The classification threshold was optimised from the default 0.5 to 0.70 to reduce false positives — an important adjustment given the class imbalance." },
        { h: "Result", p: "85.62% accuracy, 0.9094 AUC-ROC, competitive with gradient boosting methods while demonstrating neural network applicability to tabular data." },
      ],
      tags: ["Deep Learning", "Keras", "Coursework"],
      metrics: [
        { v: "85.6%", l: "accuracy" },
        { v: "0.91", l: "AUC-ROC" },
        { v: "5-fold", l: "cross-validation" },
      ],
    },
    {
      id: "alumni-career",
      name: "alumni_career.py",
      type: "DS",
      date: "2025",
      kicker: "Coursework, Predictive Analytics",
      title: "Alumni career success prediction",
      subtitle: "Scattered, inconsistent institutional data turned into one analysis-ready view.",
      coursework: true,
      links: {
        github: "https://github.com/sanjxksl/alumni-career-success",
      },
      arch: ["4 Fragmented Datasets", "Merge + Standardise", "Feature Engineering", "Random Forest Models", "CLI Predictor"],
      body: [
        { p: "Predict salary and career outcomes for university alumni given their role and location. The institutional problem is that alumni data lives across fragmented, inconsistent files that can't be used for any analysis as-is." },
        { h: "Data Preparation", p: "Merged four separate alumni datasets with salaries stored in incompatible formats — USD, INR, lakhs per annum, monthly figures. Built a pipeline to standardise, convert, and unify all records into a single usable dataset." },
        { h: "Models", p: "A Random Forest model for salary prediction, evaluated with MAE and R². A second classifier for binary career success (above or below median salary) with balanced class weights, evaluated across accuracy, AUC-ROC, and precision-recall." },
        { h: "Interface", p: "An interactive command-line tool that predicts salary and career success for any combination of role and country — useful for curriculum planning and outcome reporting." },
      ],
      tags: ["Random Forest", "Python", "Coursework"],
      metrics: [
        { v: "4", l: "datasets merged" },
        { v: "2", l: "prediction models" },
      ],
    },
  ],

  competitions: [
    {
      id: "koru",
      name: "koru_thirdplace.md",
      type: "CASE",
      date: "Nov 2025",
      kicker: "Finalist, Koru Problem Hunt",
      title: "Koru Problem Hunt, <em>ThirdPlace</em>",
      subtitle: "Mixed-methods research, a dual-sided marketplace, and the friction trinity.",
      body: [
        { h: "Outcome", p: "Finalist. Designed ThirdPlace, a dual-sided marketplace connecting hobby studios and hobbyists through a credit-based subscription model. Identified a white space no competitor occupied." },
        { h: "The Problem", p: "Hobby participation has three dominant barriers: cost (82%), scheduling (84%), and discovery (90%). Studios lose roughly $300 per unfilled class and operate at only 51% average capacity. No existing platform addresses both sides of this equation." },
        { h: "Research", p: "A quantitative survey (79% aged 18–24, equal gender split) and eight in-depth interviews across hobbyists and studio owners. The survey quantified the three barriers. The interviews revealed what studios actually worried about — commission structure, trial-to-member conversion — and what they actually wanted: booking automation, new member acquisition, predictable revenue." },
        { h: "Segmentation", p: "The hobbyist market split into two profiles: Explorers (variety-seekers blocked by scheduling) and Connectors (community-builders blocked by upfront commitment). Connectors were recommended as the initial target based on higher retention potential." },
        { h: "Product", p: "ThirdPlace combined consolidated discovery, a social experience layer with group bookings and gamification, and tiered credit-based pricing. Studios keep full pricing control. Commission is fixed and below Groupon's 50%. A hypothesis register was built across desirability, feasibility, and viability — each assumption assigned a risk level and a specific test design." },
        { h: "Market Sizing", p: "TAM $45B+, SAM $3.6B, SOM $9–15M over three years." },
      ],
      tags: ["Product Strategy", "Mixed-Methods Research", "Consumer Tech"],
      metrics: [
        { v: "82%", l: "cost barrier" },
        { v: "84%", l: "schedule barrier" },
        { v: "90%", l: "discovery barrier" },
      ],
    },
    {
      id: "mma",
      name: "mma_datathon.md",
      type: "CASE",
      date: "Jan 2026",
      kicker: "1st place, Rotman MMA Datathon",
      title: "Rotman MMA Datathon",
      subtitle: "Six thousand hours of web traffic, causal inference, and a budget reallocation.",
      body: [
        { h: "Outcome", p: "First place out of all participating teams, Rotman MMA Datathon, January 2026." },
        { h: "The Problem", p: "A retail brand operating across Canada and the US wanted to evaluate whether its paid search campaigns were actually driving traffic — or whether the traffic would have come anyway. Simply correlating ad spend with visits gives the wrong answer because organic and paid traffic move together for reasons unrelated to the campaign." },
        { h: "The Method", p: "Causal inference applied to 6,865 hours of web traffic data to isolate the campaign's true impact from the organic baseline. Separating what the campaign caused from what was already happening is where most analyses of this type go wrong." },
        { h: "The Findings", p: "35% positive ROI in the US. Loss-making spend in Canada. Recommendation: reallocate $75,000–$90,000 in paid search budget from Canada to the US. Specific enough to act on the next day." },
      ],
      tags: ["Causal Inference", "Marketing Analytics", "Python"],
      metrics: [
        { v: "1st", l: "of all teams" },
        { v: "+35%", l: "US ROI" },
        { v: "$75–90K", l: "budget reallocation" },
      ],
    },
    {
      id: "rdc",
      name: "rdc_compass.md",
      type: "CASE",
      date: "Mar 2026",
      kicker: "Finalist (top 7 of 43), Rotman Design Challenge",
      title: "Rotman Design Challenge, <em>Compass</em>",
      subtitle: "An AI agent inside Manulife's app to close the health-wealth gap.",
      body: [
        { h: "Outcome", p: "Finalist, top 7 of 43 teams, Rotman Design Challenge 2026. Designed for Manulife." },
        { h: "The Problem", p: "73% of users leave health benefits unused — not because the products are bad, but because the system is too complex to navigate. This is a navigability failure, not a product failure. That distinction changes everything about what the solution needs to be." },
        { h: "Research", p: "Seven empathy interviews and 38 survey responses revealed a compounding problem: people who can't access their benefits incur out-of-pocket costs that add up over time. Three failure modes emerged: users don't know what they have, can't find it when they need it, and aren't reminded at the moments it matters." },
        { h: "The Product", p: "Compass: an AI agent embedded in Manulife's existing app, connected across Group Benefits, Vitality, and Individual Insurance. A conversational interface answers questions in plain language. An event-trigger engine detects life signals — job change, new dependent, policy renewal — and surfaces relevant coverage at the exact moment a user would otherwise miss it. The trigger layer is what makes it different from a better search bar." },
        { h: "Validation", p: "87% of users said they would use Compass to find unused benefits, 79% to understand their coverage, and 62% rated it 7–10 out of 10 for usefulness." },
      ],
      tags: ["FinTech", "Product Design", "LLM Architecture", "User Research"],
      metrics: [
        { v: "73%", l: "benefits unused" },
        { v: "87%", l: "would adopt" },
        { v: "7/43", l: "finalists" },
      ],
    },
  ],

  learning: [
    { hash: "a1f9d02", date: "2026·Q2", branch: "QUANT FINANCE",
      msg: "Studying options pricing and asset pricing theory",
      desc: "Working through quantitative finance: options, derivatives, and asset pricing models. Building the theoretical layer underneath the empirical work done in PEAD and ESG.",
      current: true },
    { hash: "b3c1e77", date: "2026·Q2", branch: "MLOPS",
      msg: "Rebuilding credit risk model for production",
      desc: "Revisiting the credit risk counterfactual project from 2025. Hardening the inference pipeline, deployment architecture, and monitoring layer to production standard on SageMaker." },
    { hash: "7a2c19f", date: "2026·Q2", branch: "PRODUCT",
      msg: "Compass,LLM agent for Manulife (RDC finals)",
      desc: "Three-layer architecture with event triggers on life signals. The health-wealth feedback loop is real and measurable. Top 7 of 43 teams, Rotman Design Challenge 2026." },
    { hash: "d8a04bc", date: "2026·Q1", branch: "EMPIRICAL FINANCE",
      msg: "PEAD replication and ESG returns study",
      desc: "Ball and Brown (1968) on CRSP/Compustat. Then co-authored an ESG study across 20,764 firm-years. The return signal collapses once earnings news enters the model. The market prices ESG through fundamentals." },
    { hash: "e4f1b03", date: "2026·Q1", branch: "RAG / LLM",
      msg: "CIBC: embedded fieldwork then RAG agent for AML scoping",
      desc: "Two weeks of ethnographic observation before any architecture decision. Built a RAG-based exam-scoping assistant with a Streamlit UI and Databricks roadmap. Deepening LLM application design through the Stripe RAG agent project and a dedicated course alongside." },
    { hash: "c9a7d51", date: "2026·Q1", branch: "CAUSAL INFERENCE",
      msg: "1st place,MMA Datathon",
      desc: "Causal inference on paid-search web traffic. Learned to separate signal from correlation before recommending a $75-90K spend shift across Canada and the US markets." },
  ],

  gallery: [
    'Celebrating our contribution to Rotman as Ambassadors',
    'Presenting at the Rotman Datathon 2026 finals',
    'Orientation for Rotman\'s Master of Management Analytics',
    'Presenting at the Manulife RDC Case Competition finals',
    'First place at the Datathon Prize Ceremony',
    'Presenting at the Koru Case Competition finals',
    'Design for Future workshop with students from across North America',
    'Showcasing our work at CIBC to the Rotman panel',
  ],

  personality: {
    quote: "I cannot engage with anything at surface level. I need to understand the full system before I trust myself to say or build anything.",
    paragraphs: [
      "What genuinely excites me is problem solving. I love playing with data, building models, testing hypotheses, and seeing where the conclusions land.",
      "Through engineering, product design, and now analytics at Rotman, I have deliberately built a toolkit — user empathy, statistical modelling, ML, financial data analysis — because I want to be able to solve these kinds of problems. Especially the ones where the deeper you go, the stronger the signal gets. And, that is where my passion lives.",
      "Apart from work, I love to write and I have been a dancer. Fun Fact: The first time I performed on stage was when I was 5. I love Linkin Park and I listen to a lot of Indian niche r&b and hip hop artists. I tend to always find new hobbies to keep life exciting and the most recent one is baking!",
    ],
  },

  now: {
    updated: "this week",
    reading: [
      { title: "Inspired", author: "Marty Cagan", note: "rereading the parts on product discovery; what makes a model land in front of a real user." },
      { title: "The Ballad of Never After", author: "Stephanie Garber", note: "the kind of book i save for the train. fairy tale logic, sharper than it looks." },
    ],
    studying: [
      { title: "quant finance", note: "options pricing and asset management. learning to read the math the way traders read it, not the way textbooks present it." },
      { title: "MLOps", note: "specifically, deploying a real app end to end. moving from notebooks to something with a uptime expectation." },
    ],
    listening: ["Chaar Diwari", "Mokita", "Sabrina Carpenter"],
    thinking: "what changes when a model has to defend its answer to the person it affected. most of my projects keep ending up here.",
  },


  education: [
    { year: "2026", school: "University of Toronto", program: "Rotman School of Management,Master of Management Analytics" },
    { year: "2025", school: "IIIT Design & Manufacturing Kancheepuram", program: "B.Tech, Mechanical Engineering · Minor in Product Design" },
  ],

  achievements: [
    "1st Place,Koru Problem Hunt, 2025",
    "1st Place,Rotman MMA Datathon, 2026",
    "Finals (Top 7 / 43),Rotman Design Challenge, 2026",
    "Founded Alumni Association & Alumni Office at IIITDM (1,270+ records, 350 to 550 attendees)",
    "AWS ML Engineer Associate,in progress",
  ],
};
